apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-listener-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-listener
  template:
    metadata:
      labels:
        app: test-listener
    spec:
      containers:
        - name: test-listener
          image: swunderlich/listener
